application:
  name: "software odontológico"
  version: "1.0.0"
  port: "8080"

connection:
  mysql:
    host: 'localhost'
    port: 3306
    username: software
    password: odontologico
    db: software_odontologico
    connect_timeout: 4

  mongodb:
    host_port: 'cluster0.47zut.mongodb.net'
    username: 'fernandobenavides72'
    password: 'X1rnGYF3La3AzHGd'
    db: 'software_odontologico'